name: "Fly CI"

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup Flyctl
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Setup site source code
        shell: pwsh
        run: |
          $wordpressExtensions = @{ plugins = '${{ secrets.WORDPRESS_PLUGINS }}'; themes = '${{ secrets.WORDPRESS_THEMES }}' }
          ./bin/wordpress.ps1
      - name: Get Flyctl config
        env:
          FLY_CONFIG: ${{ secrets.FLY_CONFIG }}
        run: base64 -d <<< "$FLY_CONFIG" > fly.toml
      - name: Publish site
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy
